### ISSUE TITLE
How can we add expandable row property 

### ISSUE THREAD

**Issue by Harmeetkaur01** [relair/material-dynamic-table#32]
I'm using this library for dynamic table building. I'm able to do almost all the functionalities part from the expandable row.
Can anyone help me out for perform the same action

**Comment by relair** [comment]
Unfortunately it is not supported, you should probably look into using expansion panel to do that instead of table https://material.angular.io/components/expansion/overview
You could try do something with rowClick event changing something for your custom cells, but that may be complicated to do.
Generally I would just recommend using a modal dialog to display details of a row, rather than try to expand it as it is much more mobile friendly.
